name: Shared workflow

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: inject Shared workflow
        run: echo Hello from Shared workflow
