name: Template with Shared workflow steps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from Octo Organization
  call-shared-workflow:
    uses: ./.github/workflows/common-workflow.yml
